apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "name" . }}
        release: {{ .Release.Name }}
        version: "0.1"
    spec:
      containers:
        - name: docker-daemon
          image: docker:20-dind
          securityContext:
            privileged: true
          env:
            - name: DOCKER_TLS_CERTDIR
              value: ""
          volumeMounts:
            - mountPath: /var/lib/docker
              name: docker-graph-storage
        - name: vsts-agent
          image: docker.io/thegalah/ado-agent:dind
          env:
            - name: AZP_URL
              valueFrom:
                secretKeyRef:
                  name: ado-agent-secret
                  key: azp_url
            - name: AZP_TOKEN
              valueFrom:
                secretKeyRef:
                  name: ado-agent-secret
                  key: azp_token
            - name: AZP_POOL
              valueFrom:
                secretKeyRef:
                  name: ado-agent-secret
                  key: azp_pool
            - name: VSTS_WORK
              value: /workspace
            - name: DOCKER_HOST
              value: tcp://0.0.0.0:2375
          volumeMounts:
            - mountPath: /workspace
              name: workspace
      volumes:
        - name: docker-graph-storage
          emptyDir: {}
        - name: workspace
          persistentVolumeClaim:
            claimName: workspace