apiVersion: v1
kind: Secret
metadata:
  name: ado-agent-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  azp_token: {{ .Values.PAT | b64enc }}
  azp_url: {{ .Values.AZP_URL | b64enc }}
  azp_pool: {{ .Values.AZP_POOL | b64enc }}
