apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "name" . }}
        release: {{ .Release.Name }}
        version: "0.1"
    spec:
      containers:
        - name: vsts-agent
          image: microsoft/vsts-agent:ubuntu-16.04-docker-18.06.1-ce-standard
          env:
            - name: VSTS_ACCOUNT
              valueFrom:
                secretKeyRef:
                  name: vsts-agent-secret
                  key: account
            - name: VSTS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: vsts-agent-secret
                  key: token
            - name: VSTS_POOL
              valueFrom:
                secretKeyRef:
                  name: vsts-agent-secret
                  key: pool
            - name: VSTS_WORK
              value: /workspace
          volumeMounts:
            - mountPath: /var/run/docker.sock
              name: docker-volume
      volumes:
        - name: docker-volume
          hostPath:
            path: /var/run/docker.sock
        volumeMounts:
          - name: workspace
            mountPath: /workspace
  volumeClaimTemplates:
  - metadata:
      name: workspace
    spec:
      accessModes: [ ReadWriteOnce ]
      storageClassName: default
      resources:
        requests:
          storage: 20Gi