apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "name" . }}
        release: {{ .Release.Name }}
        version: "0.1"
    spec:
      containers:
        - name: vsts-agent
          image: docker.io/thegalah/ado-agent:latest
          env:
            - name: VSTS_ACCOUNT
              valueFrom:
                secretKeyRef:
                  name: vsts-agent-secret
                  key: account
            - name: VSTS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: vsts-agent-secret
                  key: token
            - name: VSTS_POOL
              valueFrom:
                secretKeyRef:
                  name: vsts-agent-secret
                  key: pool
            - name: VSTS_WORK
              value: /workspace
          volumeMounts:
            - mountPath: /var/run/docker.sock
              name: docker-volume
            - mountPath: /workspace
              name: workspace
      volumes:
        - name: docker-volume
          hostPath:
            path: /var/run/docker.sock
        - name: workspace
          persistentVolumeClaim:
            claimName: workspace