apiVersion: v1
kind: Secret
metadata:
  name: vsts-agent-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  token: {{ .Values.vstsToken | b64enc }}
  account: {{ .Values.vstsAccount | b64enc }}
  pool: {{ .Values.vstsPool | b64enc }}
